sudo: required
os: osx

language: node_js
node_js:
  - "8"

branches:
  only:
    - master
  except:
    - gh-pages
  
services:
  - docker

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g
  - docker build -t a:a .
      






 